# Generated by Django 3.2.8 on 2022-03-05 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_auto_20220305_2145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminsignup',
            old_name='name',
            new_name='userName',
        ),
        migrations.RemoveField(
            model_name='adminsignup',
            name='username',
        ),
    ]
