# Generated by Django 3.2.8 on 2022-03-06 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddQuotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotes', models.ImageField(upload_to='')),
                ('userName', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.usersignup')),
            ],
        ),
    ]
