# Generated by Django 3.2.8 on 2022-03-06 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_addquotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addquotes',
            name='userName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.usersignup'),
        ),
    ]
