# Generated by Django 3.2.8 on 2022-03-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_addquotes_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addquotes',
            name='quotes',
            field=models.SlugField(max_length=1000),
        ),
    ]
