# Generated by Django 3.2.8 on 2022-03-06 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_addquotes_quotes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApproveQuotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotes', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.addquotes')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.usersignup')),
            ],
        ),
    ]
