# Generated by Django 4.0.4 on 2022-05-16 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_approvequotes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_key', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.approvequotes')),
                ('like_user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.usersignup')),
            ],
        ),
    ]
